---
title: "New Insights into PCA + Varimax for Psychological Researchers"
subtitle: "A short commentary on Rohe & Zeng (2023)"
author:
  - name: Florian Pargent
    orcid: 0000-0002-2388-553X
    affiliation: Department of Psychology, LMU Munich
    email: florian.pargent@psy.lmu.de
    corresponding: true
  - name: David Goretzko
    affiliation: Utrecht University
  - name: Timo von Oertzen
    affiliation: Bundeswehr University Munich and Max Planck Institute for Human Development
date: today
bibliography: references.bib
csl: apa.csl
citation:
  url: "https://lmu-osc.github.io/myquartomanuscript/"
---

```{r}
#| message: false
phonedata_items = read.csv2("datasets/Items.csv")
phonedata_items = na.omit(phonedata_items[, 3:302])
phonedata_sensing = readRDS(file = "datasets/clusterdata.RDS")
phonedata_sensing = phonedata_sensing[, c(1:1821)]
```

:::{.callout-important}
This document is **an updated copy** of a [published commentary](https://doi.org/10.1093/jrsssb/qkad054), to showcase [Quarto manuscripts](https://quarto.org/docs/manuscripts/) in our [Quarto workshop](https://lmu-osc.github.io/introduction-to-Quarto/). The official online repository of our published commentary can be found [here](https://osf.io/5symf/).
:::

### Commentary

As psychologists, we appreciate Rohe & Zeng's (R&Z; @rohe2023vintage) new insights into “vintage” principal component analysis with varimax rotation (PCA+VR). Theories of intelligence and personality, perhaps psychology's contributions best known outside of our field, have been a direct product of PCA. PCA+VR is still widely used for developing and evaluating psychological tests and questionnaires, although the literature has fought against it in favor of more complex factor analytic techniques [@fokkema2017how].

In our opinion, abandoning the simpler PCA(+VR) is a mistake and R&Z refute a common argument by proving that PCA+VR *can* perform statistical inference in latent variable models: The factor indeterminacy problem which plagued VR since its invention only applies for the special case of normally distributed factors. For any other distribution, perfect factor indeterminacy does not apply, although identifiability might be weak. However, distributions producing sparse components fulfill a *sufficient* leptokurtic condition, which can be confirmed by simple diagnostics.

Because the results are complicated, we relate them to psychological applications. The examples in R&Z only deal with sparse binary network data, but in typical psychological applications, the $A$ matrix consists of responses of $n$ persons to $d$ items which are either binary (e.g., intelligence tests), integer-valued (e.g., personality questionnaires) or continuous (e.g., digital sensors). Psychologists are often interested in whether i) items can be structured in a simple way to represent a small number of meaningful components, and ii) those components can be interpreted as psychological constructs that describe interindividual differences. R&Z show that "radial streaks" in the rotated loading matrix $\hat{Y}$ suggest that item loadings are identified and can be estimated with PCA+VR from the data. Similarly, streaks in the component matrix $\hat{Z}$ suggest that person scores can be estimated.

However, we question whether streaks are common in psychology with regard to both aspects. Test and questionnaire items are traditionally designed to measure only a single construct, so "simple structure" reflected by streaks in $\hat{Y}$ might be expected. Psychological constructs are often conceptualized as roughly normally distributed, so streaks in $\hat{Z}$ seem more questionable. In our online materials (<https://osf.io/5symf/>), we analyze a dataset [@stachl2020predicting] containing both personality items ($n =`r nrow(phonedata_items)`$, $d =`r ncol(phonedata_items)`$) and smartphone sensing variables ($n =`r nrow(phonedata_sensing)`$, $d =`r ncol(phonedata_sensing)`$). Streaks were found only in $\hat{Y}$ but not in $\hat{Z}$. It is also a cautionary example of how imputation of missing values in combination with inappropriate data processing seemingly produce streaks in $\hat{Z}$ that belong to uninterpretable components. Degree normalization as discussed in R&Z is not suitable for many psychological datasets and other procedures like z-standardization are often required to detect meaningful factors. Finally, we demonstrate R&Z's side result that the matrix $\hat{Z}\hat{B}$ from PCA+VR can estimate person scores simulated from oblique leptokurtic components.

In our opinion, the main usefulness of PCA+VR not necessarily stems from its ability to estimate latent variable models. PCA excels at providing meaningful descriptions in practical applications but R&Z's and our examples also show that there is rarely a single definite structure. Components are most useful when they predict other meaningful quantities, regardless of the assumed epistemological nature of psychological constructs [@yarkoni2020implicit].

### References

::: {#refs}
:::
